apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limitrange
  namespace: ns-dev
spec:
  limits:
  - type: Container
    default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    max:
      cpu: "200m"
      memory: "256Mi"
